# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di7sx9RjA58KvsfgWG2QKD2eB6VQM97a
"""

for i in range(1,5):
    for j in range(1,i):
       print(" ",end=" ")

    # star
    for k in range(i,5):
       print("*",end=" ")
    print("")

for i in range(1,5):
    for j in range(i,4):
        print(" ",end="")

    for k in range(1,2*i):
        print("*",end="")
    print(" ")

for i in range(1,5):
    for j in range(i,4):
       print(" ",end="")
    #star
    for k in range(1,i+1):
        print("*",end=" ")

    print("")

#list
#list is a collection of element
#","
#multiple form of value

mylist=[10,20,"a"]
print(mylist,type(mylist))

#update (index)
mylist=[10,20,"a"]
mylist.extend(["hey"])

print(mylist)

mylist=[10,20,"a"]
help(mylist)
print(mylist)

mylist=[10,20,"a",10,25]
mylist.remove(10)

print(mylist)

for i in [10,20,30,"abc"]:
    print(i)

x=[]
for i in [10,"20",30,"abc"]:
    if (type(i)==int):
         x.append(i)

print(x)

#tuple
#immutable
#()
mytuple=(10,20)
print(type(mytuple))

mytuple=(10,20)
print("old",id(mytuple))
mytuple=mytuple+(30,40)
print("new",id(mytuple))
print(mytuple)

